/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TranslationRecord = IDL.Record({
  'id' : IDL.Nat,
  'outputContent' : IDL.Text,
  'spokenLanguage' : IDL.Text,
  'mode' : IDL.Text,
  'timestamp' : IDL.Int,
  'inputContent' : IDL.Text,
  'signLanguage' : IDL.Text,
});
export const UserPreferences = IDL.Record({
  'preferredSpokenLanguage' : IDL.Text,
  'preferredSignLanguage' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTranslationRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearTranslationHistory' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTranslationHistory' : IDL.Func(
      [],
      [IDL.Vec(TranslationRecord)],
      ['query'],
    ),
  'getUserPreferences' : IDL.Func([], [UserPreferences], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserPreferences' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TranslationRecord = IDL.Record({
    'id' : IDL.Nat,
    'outputContent' : IDL.Text,
    'spokenLanguage' : IDL.Text,
    'mode' : IDL.Text,
    'timestamp' : IDL.Int,
    'inputContent' : IDL.Text,
    'signLanguage' : IDL.Text,
  });
  const UserPreferences = IDL.Record({
    'preferredSpokenLanguage' : IDL.Text,
    'preferredSignLanguage' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTranslationRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearTranslationHistory' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTranslationHistory' : IDL.Func(
        [],
        [IDL.Vec(TranslationRecord)],
        ['query'],
      ),
    'getUserPreferences' : IDL.Func([], [UserPreferences], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserPreferences' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };